# Usa l'immagine Node per costruire l'app
FROM node:18 AS build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build --prod

# Usa un'immagine Nginx per servire l'app
FROM nginx:alpine
COPY --from=build /app/dist/your-angular-app-name /usr/share/nginx/html
EXPOSE 80
