version: '3.8'
services:
  CREA-PREVENTIVO-RS:
    build:
      context: ./CREA-PREVENTIVO-RS
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

  CREA-PREVENTIVO-PF:
    build:
      context: ./CREA-PREVENTIVO-PF
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
