version: '3.8'
services:
  backend:
    build:
      context: ./CREA-PREVENTIVO-RS/src/main/resources
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

  frontend:
    build:
      context: ./CREA-PREVENTIVO-PF/src/main/angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
